// <auto-generated />
using CBURate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CBURate.Migrations
{
    [DbContext(typeof(CBUContext))]
    partial class CBUContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CBURate.IncomingModel", b =>
                {
                    b.Property<int>("Identifikator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Identifikator"));

                    b.Property<string>("Ccy")
                        .HasColumnType("text");

                    b.Property<string>("CcyNm_EN")
                        .HasColumnType("text");

                    b.Property<string>("CcyNm_RU")
                        .HasColumnType("text");

                    b.Property<string>("CcyNm_UZ")
                        .HasColumnType("text");

                    b.Property<string>("CcyNm_UZC")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<string>("Diff")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Nominal")
                        .HasColumnType("text");

                    b.Property<string>("Rate")
                        .HasColumnType("text");

                    b.HasKey("Identifikator");

                    b.ToTable("models");
                });
#pragma warning restore 612, 618
        }
    }
}
